#!/bin/bash
#PBS -l select=1:ncpus=24:mem=120gb
#PBS -P CSCI1142
#PBS -q smp
#PBS -l walltime=33:00:00
#PBS -o /mnt/lustre/users/eraine/jobs/ssga_unfinished_9.out
#PBS -e /mnt/lustre/users/eraine/jobs/ssga_unfinished_9.err
#PBS -m abe
#PBS -M rnxemi001@myuct.ac.za

ulimit -s unlimited

module purge
module load chpc/BIOMODULES anaconda/3
module load chpc/BIOMODULES roborobo4

eval "$(conda shell.bash hook)"

conda activate roborobo

cd /mnt/lustre/users/eraine/hons-project4
nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE

SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_ssga-e-d-09/checkpoints/gen_84.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/ssga/ssga-easy_maze-difficult.properties ssga-e-d-10
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/ssga/ssga-easy_maze-difficult.properties ssga-e-d-11
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/ssga/ssga-easy_maze-difficult.properties ssga-e-d-12

conda deactivate