# == ENVIRONMENT CONFIGURATION ==
# Evolutionary Algorithm: Homogenous SSGA 
# Task Difficulty: Medium

# =-=-=-=-=-=-=-=-=-=- #
# IMPORTANT PARAMETERS #
# =-=-=-=-=-=-=-=-=-=- #

pEasyLevel = false                      # Disable Easy Level
pMediumLevel = true                     # Enable Medium Level (ensures dynamic sinkholes occur)
pDifficultLevel = false                 # Disable Difficult Level

pSimulationGenerations = 100            # number of generations
pSimulationLifetime = 800               # number of time steps per simulation
pPopulationSize = 100                   # number of genomes in the population
pEvaluationTrials = 3                   # number of simulations per individual for fitness averaging

pCrossoverProbability = 0.5
pMutationProbability = 0.2
pCheckpointInterval = 1
# pDynamicProgressOutput = false
pDynamicProgressOutput = true # For testing

pSwarmFitnessAlgorithm = COUNT        # CROWD, DWELL or COUNT
pEvolutionAlgorithm = SHOM            # SHOM, DNS or NSS-LC
pBehaviourFeatures = [PEN,DOG,SHEEP]  # PEN, DOG and/or SHEEP

pTaskEnvironment = CAPTURE            # CONTAIN or CAPTURE

pNumberOfDogs = 10                    # number of sheep = gInitialNumberOfRobots - pNumberOfDogs
gInitialNumberOfRobots = 30

# gathering pen parameters
gNbOfLandmarks = 1
VisibleLandmarks = true
gLandmarkRadius = 100
landmark[0].x = 300
landmark[0].y = 300
pTargetZoneCoordX = 300
pTargetZoneCoordY = 300
pTargetZoneRadius = 100
pTargetZoneSpawning = false

# agent parameters
gSensorRange = 100

# dog parameters
# Added sinkhole radar sensor
dInputNodes = 11                      # 1 bias + 4 radar sensors + 1 landmark sensor (each with distance [0, 1] and angle [-1, 1]) -- editing will require code change
dHiddenNodes = 10
dOutputNodes = 2                      # translation [-1, 1] and rotation [-1, 1] -- editing will require code change
dMaxTranslationSpeed = 1.0
dSensorLeftFOV = -90
dSensorRightFOV = 90
dSensorRange = 100                    # make sure gSensorRange >= dSensorRange

# sheep parameters
sWallAvoidanceRadius = 15.0
sDogAvoidanceRadius = 50.0
sSheepAvoidanceRadius = 5.0
sSinkholeAvoidanceRadius = 10.0 # For testing, check best value for this
sTargetZoneAvoidanceRadius = 50.0
sTargetZoneAvoidanceStrength = 0.25
sFlockingCoherence = 0.1
sFlockingAlignment = 0.05
sTranslationSpeed = 1.0
sSensorLeftFOV = -180
sSensorRightFOV = 180
sSensorRange = 50                    # make sure gSensorRange >= sSensorRange


# =-=-=-=-=-=-=-=- #
# OTHER PARAMETERS #
# =-=-=-=-=-=-=-=- #

# gNbOfPhysicalObjects = 0 # Original
gNbOfPhysicalObjects = 5 # For sinkhole objects

gDisplayMode = 0
# gBatchMode = true
gBatchMode = false # For testing

gRandomSeed = -1

# gVerbose = false 
gVerbose = true # For testing

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

gMaxIt = -1

# gEvaluationTime =   400
gEvaluationTime =   100 # For testing

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#
# general file information
#

ConfigurationLoaderObjectName = DummyConfigurationLoader

gRobotMaskImageFilename = data/minirobot-mask.bmp
gRobotDisplayImageFilename = data/minirobot-mask.bmp
gRobotSpecsImageFilename = data/minirobot-specs-24sensors.bmp

# environment
gForegroundImageFilename = data/env_600_foreground_easy.bmp
gEnvironmentImageFilename = data/env_600_environment_easy.bmp 
gBackgroundImageFilename = data/env_600_background.bmp
gFootprintImageFilename = data/env_600_footprints.bmp
gArenaWidth = 600
gArenaHeight = 600


gLogDirectoryname = output/logs
gLogFilename = trash.log # if commented, create a time-stamped file.
gLogCommentText = (under-development)

gSnapshots = false # take snapshots
gSnapshotsFrequency = 10 # every N generations


# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# 
# Other parameters
#

# general purpose

gPauseMode = false
gDisplaySensors = 0   # 0: no, 1: only-contact, 2: all + contacts are red, 3: all (same color)
gDisplayTail = true
gRobotDisplayFocus = false
gDisplayGroundCaption = false
gNiceRendering = true
SlowMotionMode = false
gUserCommandMode = false
gRobotLEDdisplay = true

gFastDisplayModeSpeed = 60
gFramesPerSecond = 60

gLocationFinderMaxNbOfTrials = 1000 # 100?

gRobotIndexFocus = 0

gFootprintImage_restoreOriginal = true

gNumberOfRobotGroups = 1 # unused

gPhysicalObjectIndexStartOffset = 1
gRobotIndexStartOffset = 1048576  # 0x100000

# Monitoring

gVideoRecording = false # significantly slow down simulation
gTrajectoryMonitor = false  # significantly slow down simulation

gInspectorMode = false
gInspectorAgent = false
gMonitorRobot = false

# Inspector cursor (''god mode'')

gInspectorCursorHorizontalSpeed = 1
gInspectorCursorVerticalSpeed = 1
gInspectorAgentXStart = 1
gInspectorAgentYStart = 1

# robot dynamics and structure

gMaxTranslationalSpeed = 2  # value btw 0+ and robot width in pixels
gMaxTranslationalDeltaValue = 2 	# value btw 0+ and gMaxTranslationalSpeed
gMaxRotationalSpeed = 30

gInspectorCursorMaxSpeedOnXaxis = 5
gInspectorCursorMaxSpeedOnYaxis = 10

gLocomotionMode = 0




# =-=-=-=-=-=

# simulation parameters

gMonitorPositions = false # slow down if true.

# =-=-=-=-=-=



# Agents

gAgentsInitAreaX = 0
gAgentsInitAreaY = 0
gAgentsInitAreaWidth = 590 # gArenaWidth-10
gAgentsInitAreaHeight = 590 # gArenaHeight-10

# Physical objects

gPhysicalObjectsVisible = true
gPhysicalObjectsRedraw = false

gPhysicalObjectsInitAreaX = 10
gPhysicalObjectsInitAreaY = 10
gPhysicalObjectsInitAreaWidth = 590 # gArenaWidth-10
gPhysicalObjectsInitAreaHeight = 590 # gArenaHeight-10
gPhysicalObjectDefaultType = 1 # ########## For testing check what this is
gPhysicalObjectDefaultRelocate = false
gPhysicalObjectDefaultOverwrite = false
gPhysicalObjectDefaultRadius = 6
gPhysicalObjectDefaultFootprintRadius = 10
gPhysicalObjectDefaultDisplayColorRed = 192
gPhysicalObjectDefaultDisplayColorGreen = 255
gPhysicalObjectDefaultDisplayColorBlue = 128
gPhysicalObjectDefaultSolid_w = 16
gPhysicalObjectDefaultSolid_h = 16
gPhysicalObjectDefaultSoft_w = 22
gPhysicalObjectDefaultSoft_h = 22

gPhysicalObjectDefaultRegrowTimeMax = 100

# For sinkhole objects
gPhysicalObjectsStep = true # Enables physical objects to update or change during the simulation (using their step() function)

# Parameters for sinkhole objects
gNumberOfSinkholes = 5 

physicalObject[0].pytype = sinkhole
physicalObject[0].x = 190
physicalObject[0].y = 235
physicalObject[0].radius = 20
physicalObject[0].footprintRadius = 27 
physicalObject[0].solid_w = 40
physicalObject[0].solid_h = 40
physicalObject[0].soft_w = 40
physicalObject[0].soft_h = 40
physicalObject[0].displayColorRed = 255
physicalObject[0].displayColorGreen = 0
physicalObject[0].displayColorBlue = 0
physicalObject[0].visible = false
physicalObject[0].relocate = false
physicalObject[0].overwrite = false
physicalObject[0].regrowTimeMax = 0	# respawn after N iterations

physicalObject[1].pytype = sinkhole
physicalObject[1].x = 235
physicalObject[1].y = 190
physicalObject[1].radius = 20
physicalObject[1].footprintRadius = 27
physicalObject[1].solid_w = 40
physicalObject[1].solid_h = 40
physicalObject[1].soft_w = 40
physicalObject[1].soft_h = 40
physicalObject[1].displayColorRed = 255
physicalObject[1].displayColorGreen = 0
physicalObject[1].displayColorBlue = 0
physicalObject[1].visible = false
physicalObject[1].relocate = false
physicalObject[1].overwrite = false
physicalObject[1].regrowTimeMax = 0	# respawn after N iterations

physicalObject[2].pytype = sinkhole
physicalObject[2].x = 300
physicalObject[2].y = 170
physicalObject[2].radius = 20
physicalObject[2].footprintRadius = 27
physicalObject[2].solid_w = 40
physicalObject[2].solid_h = 40
physicalObject[2].soft_w = 40
physicalObject[2].soft_h = 40
physicalObject[2].displayColorRed = 255
physicalObject[2].displayColorGreen = 0
physicalObject[2].displayColorBlue = 0
physicalObject[2].visible = false
physicalObject[2].relocate = false
physicalObject[2].overwrite = false
physicalObject[2].regrowTimeMax = 0	# respawn after N iterations

physicalObject[3].pytype = sinkhole
physicalObject[3].x = 365
physicalObject[3].y = 190
physicalObject[3].radius = 20
physicalObject[3].footprintRadius = 27
physicalObject[3].solid_w = 40
physicalObject[3].solid_h = 40
physicalObject[3].soft_w = 40
physicalObject[3].soft_h = 40
physicalObject[3].displayColorRed = 255
physicalObject[3].displayColorGreen = 0
physicalObject[3].displayColorBlue = 0
physicalObject[3].visible = false
physicalObject[3].relocate = false
physicalObject[3].overwrite = false
physicalObject[3].regrowTimeMax = 0	# respawn after N iterations

physicalObject[4].pytype = sinkhole
physicalObject[4].x = 410
physicalObject[4].y = 235
physicalObject[4].radius = 20
physicalObject[4].footprintRadius = 27
physicalObject[4].solid_w = 40
physicalObject[4].solid_h = 40
physicalObject[4].soft_w = 40
physicalObject[4].soft_h = 40
physicalObject[4].displayColorRed = 255
physicalObject[4].displayColorGreen = 0
physicalObject[4].displayColorBlue = 0
physicalObject[4].visible = false
physicalObject[4].relocate = false
physicalObject[4].overwrite = false
physicalObject[4].regrowTimeMax = 0	# respawn after N iterations



gEnergyItemDefaultMode = 0
gEnergyItemDefaultInit = 100

gSensoryInputs_distanceToContact = true
gSensoryInputs_physicalObjectType = true
gSensoryInputs_isOtherAgent = true
gSensoryInputs_otherAgentGroup = true
gSensoryInputs_otherAgentOrientation = true
gSensoryInputs_isWall = true
gSensoryInputs_groundSensors = true
gSensoryInputs_landmarkTrackerMode = 0
gSensoryInputs_distanceToLandmark = true
gSensoryInputs_orientationToLandmark = true
gSensoryInputs_energyLevel = true
gEnergyLevel = false
gEnergyRefill = false
gEnergyMax = 100
gEnergyInit = 100
gReentrantMapping_motorOutputs = false
gReentrantMapping_virtualOutputs = false
gVirtualOutputs = 0
gDisplayScreenHeight = 600 # gArenaHeight
gDisplayScreenWidth = 600 # gArenaWidth
gArrowLength = 16
gLocationFinderExitOnFail = true
gOutputImageFormat = PNG
gCustomSnapshot_niceRendering = true
gCustomSnapshot_showLandmarks = true
gCustomSnapshot_showObjects = true
gCustomSnapshot_showRobots = true
gCustomSnapshot_showSensorRays = false
gMovableObjects = false