#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -P CSCI1142
#PBS -q smp
#PBS -l walltime=96:00:00
#PBS -o /mnt/lustre/users/eraine/jobs/nsslc-e-e-05.out
#PBS -e /mnt/lustre/users/eraine/jobs/nsslc-e-e-05.err
#PBS -m abe
#PBS -M rnxemi001@myuct.ac.za

ulimit -s unlimited

module purge
module load chpc/BIOMODULES anaconda/3
module load chpc/BIOMODULES roborobo4

eval "$(conda shell.bash hook)"

conda activate roborobo

cd /mnt/lustre/users/eraine/hons-project
nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE

SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-easy.properties nsslc-e-e-01
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-easy.properties nsslc-e-e-02
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-easy.properties nsslc-e-e-03
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-easy.properties nsslc-e-e-04
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-easy.properties nsslc-e-e-05

conda deactivate