#!/bin/bash
#PBS -l select=1:ncpus=24:mem=120gb
#PBS -P CSCI1142
#PBS -q smp
#PBS -l walltime=56:00:00
#PBS -o /mnt/lustre/users/eraine/jobs/nsslc-e-d-10.out
#PBS -e /mnt/lustre/users/eraine/jobs/nsslc-e-d-10.err
#PBS -m abe
#PBS -M rnxemi001@myuct.ac.za

ulimit -s unlimited

module purge
module load chpc/BIOMODULES anaconda/3
module load chpc/BIOMODULES roborobo4

eval "$(conda shell.bash hook)"

conda activate roborobo

cd /mnt/lustre/users/eraine/hons-project
nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE

SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-difficult.properties nsslc-e-d-06
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-difficult.properties nsslc-e-d-07
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-difficult.properties nsslc-e-d-08
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-difficult.properties nsslc-e-d-09
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -s config/nsslc/nsslc-easy_maze-difficult.properties nsslc-e-d-10

conda deactivate